#!/bin/bash
sudo add-apt-repository ppa:oibaf/graphics-drivers -y
sudo apt install llvm-dev libturbojpeg* libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libglx-mesa0 mesa-common-dev mesa-vulkan-drivers
