#!/bin/bash
add-apt-repository ppa:oibaf/graphics-drivers -y
apt install llvm-dev libturbojpeg* libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libglx-mesa0 mesa-common-dev mesa-vulkan-drivers
pip install git+https://github.com/pygfx/pygfx.git@main
pip install git+https://github.com/kushalkolar/fastplotlib.git@master
